{"name": "Non auth user data update failed test", "status": "passed", "start": 1732715231919, "stop": 1732715234230, "uuid": "3b88e04e-b450-4666-9bdb-cd70cda7cd61", "historyId": "6db691b8d2fc22e3370977d4006e34f3", "testCaseId": "6db691b8d2fc22e3370977d4006e34f3", "fullName": "tests.test_update_user_profile.TestUpdateUserData#test_update_user_data_non_auth_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_profile"}, {"name": "subSuite", "value": "TestUpdateUserData"}, {"name": "host", "value": "ast24help1c2"}, {"name": "thread", "value": "11252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_profile"}]}